name: CI-CD
on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Docker Login
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Docker build and push image
        uses: docker/build-push-action@v2
        with:
          context: ./src ## Folder of project with files to build image
          file: ./src/Dockerfile ## Dockerfile path
          push: true
          tags: |
            revoltaxz/rotten-potatoes:latest
            revoltaxz/rotten-potatoes:${{ github.run_number }}
  CD:
    needs: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Kubernetes set context
        uses: Azure/k8s-set-context@v1.1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.K8S_KUBECONFIG }}

      - name: Deploy to Kubernetes cluster
        uses: Azure/k8s-deploy@v1.3
        with:
          images: revoltaxz/rotten-potatoes:${{ github.run_number }}
          manifests: |
            k8s/deployment.yaml


    
