name: CI-CD
on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Docker Login
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Docker build and push image
        uses: docker/build-push@v2
        with:
          context: ./src ## Folder of project with files to build image
          file: ./src/Dockerfile ## Dockerfile path
          push: true
          tags: |
            revoltaxz/rotten-potatoes:latest
            revoltaxz/rotten-potatoes:${{ github.run_number }}

    
